import json


class PromptBuilder:

    def build_repository_prompt(
        self,
        context: dict,
        question: str
    ):

        prompt = f"""
You are an expert Software Architect, Senior Backend Engineer, and Code Reviewer.

You are given structured analysis of a GitHub repository generated by CodeSherlock.

Repository Context
==================

{json.dumps(context, indent=4)}

==================

User Question:
{question}

Instructions:

1. Answer ONLY using the provided repository context.
2. If the answer cannot be determined from the context, clearly say so.
3. Do not hallucinate.
4. Explain in simple language.
5. Use headings and bullet points whenever appropriate.
6. If asked for a learning roadmap, recommend important files first.
7. If asked about architecture, explain components and their relationships.

Return only the answer.
"""

        return prompt